sendTo: "study-participants"
studyKey: "standard"
messageType: "weekly"
nextTime: "2024-11-28-06:00:00"
period: 86400
defaultLanguage: "fr"
translations:
  - lang: "en"
    subject: "Your weekly questionnaire is ready for you"
    templateFile: "en.html"
  - lang: "de"
    subject: "Ihr wöchentlicher Fragebogen steht zum Ausfüllen bereit"
    templateFile: "de.html"
  - lang: "fr"
    subject: "Votre questionnaire hebdomadaire est prêt à être complété"
    templateFile: "fr.html"
  - lang: "it"
    subject: "Il tuo questionario settimanale ti aspetta"
    templateFile: "it.html"
